import bcrypt from "bcryptjs";
import {
  PrismaClient,
  ProductStatus,
  StaffRole,
  UserRole,
} from "@prisma/client";

const prisma = new PrismaClient();
const image = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1200&q=80`;

const categories = [
  {
    name: "Personalized Gifts",
    slug: "personalized-gifts",
    description: "Keepsakes made especially for someone dear.",
  },
  {
    name: "Rakhi & Festive",
    slug: "rakhi-festive",
    description: "Small rituals, joyful colour, and festive warmth.",
  },
  {
    name: "Home & Decor",
    slug: "home-decor",
    description: "Artisanal details for lived-in spaces.",
  },
  {
    name: "Jewelry Accessories",
    slug: "jewelry-accessories",
    description: "Hand-finished accents for everyday celebration.",
  },
];

const products = [
  [
    "Personalized Brass Name Plate",
    "personalized-brass-name-plate",
    "Hand-etched brass name plate for a new home or a thoughtful housewarming gift.",
    "A hand-etched welcome.",
    "PG-BRASS-001",
    2499,
    12,
    "personalized-gifts",
    true,
    "Name to engrave",
    28,
    "photo-1600607687939-ce8a6c25118c",
  ],
  [
    "Monogrammed Linen Keepsake Box",
    "monogrammed-linen-keepsake-box",
    "A linen-wrapped box with a hand-painted monogram for treasured little things.",
    "A place for memories.",
    "PG-LINEN-002",
    1299,
    24,
    "personalized-gifts",
    true,
    "Initials to add",
    3,
    "photo-1586023492125-27b2c045efd7",
  ],
  [
    "Custom Engraved Desk Tray",
    "custom-engraved-desk-tray",
    "Solid mango wood tray finished by hand and engraved with a personal note.",
    "Make their everyday beautiful.",
    "PG-WOOD-003",
    899,
    30,
    "personalized-gifts",
    true,
    "Message to engrave",
    45,
    "photo-1494438639946-1ebd1d20bf85",
  ],
  [
    "Handpainted Rakhi Set",
    "handpainted-rakhi-set",
    "A joyful set of two handpainted rakhis with soft cotton threads and seed beads.",
    "For the bond that keeps growing.",
    "RF-RAKHI-004",
    599,
    45,
    "rakhi-festive",
    false,
    null,
    null,
    "photo-1599552683573-16b443d7a6a3",
  ],
  [
    "Kansa Tealight Pair",
    "kansa-tealight-pair",
    "A pair of warm kansa metal tealight holders for festive evenings and quiet corners.",
    "Light, held gently.",
    "RF-KANSA-005",
    1099,
    18,
    "rakhi-festive",
    false,
    null,
    null,
    "photo-1603006905003-be475563bc59",
  ],
  [
    "Madhubani Festive Toran",
    "madhubani-festive-toran",
    "A hand-painted fabric toran inspired by the bold lines of Madhubani folk art.",
    "Welcome in colour.",
    "RF-TORAN-006",
    1499,
    15,
    "rakhi-festive",
    false,
    null,
    null,
    "photo-1604917877934-07d8d248d396",
  ],
  [
    "Block Print Table Runner",
    "block-print-table-runner",
    "A cotton table runner printed by hand with an understated botanical pattern.",
    "Set the table with story.",
    "HD-RUNNER-007",
    1199,
    20,
    "home-decor",
    false,
    null,
    null,
    "photo-1604014237800-1c9102c219da",
  ],
  [
    "Terracotta Diya Cluster",
    "terracotta-diya-cluster",
    "Six terracotta diyas shaped and fired by a family of potters in Rajasthan.",
    "For evenings that glow.",
    "HD-DIYA-008",
    749,
    50,
    "home-decor",
    false,
    null,
    null,
    "photo-1572726729207-a78d6feb18d7",
  ],
  [
    "Carved Mango Wood Bookends",
    "carved-mango-wood-bookends",
    "A sculptural pair of mango wood bookends with a softly carved sun motif.",
    "A little grounding for your shelf.",
    "HD-BOOK-009",
    1899,
    10,
    "home-decor",
    false,
    null,
    null,
    "photo-1544947950-fa07a98d237f",
  ],
  [
    "Brass Lotus Incense Holder",
    "brass-lotus-incense-holder",
    "A lotus-shaped brass holder made for incense sticks and slow morning rituals.",
    "Make room for stillness.",
    "HD-LOTUS-010",
    699,
    35,
    "home-decor",
    false,
    null,
    null,
    "photo-1519710164239-da123dc03ef4",
  ],
  [
    "Beaded Silk Potli",
    "beaded-silk-potli",
    "A festive silk potli detailed with glass beads and a soft drawstring closure.",
    "A tiny celebration to carry.",
    "JA-POTLI-011",
    999,
    22,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1612902456551-333ac5afa26e",
  ],
  [
    "Dhokra Leaf Earrings",
    "dhokra-leaf-earrings",
    "Lightweight lost-wax brass earrings with an organic leaf silhouette.",
    "Wear a little wildness.",
    "JA-EARTH-012",
    1299,
    16,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1535632066927-ab7c9ab60908",
  ],
  [
    "Kundan Hair Pin Set",
    "kundan-hair-pin-set",
    "A set of two delicate hair pins with hand-set kundan details.",
    "An heirloom feeling, every day.",
    "JA-KUNDAN-013",
    899,
    25,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1523779917675-b6ed3a42a561",
  ],
  [
    "Handwoven Cotton Stole",
    "handwoven-cotton-stole",
    "A light handwoven cotton stole with a fine zari edge for gifting or keeping.",
    "Soft colour, easy grace.",
    "JA-STOLE-014",
    1599,
    14,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1601924928374-7b7a9c1b8bde",
  ],
  [
    "Personalized Celebration Card Set",
    "personalized-celebration-card-set",
    "Five illustrated cards with space for a name, note, or small blessing.",
    "Say it in your own words.",
    "PG-CARD-015",
    449,
    60,
    "personalized-gifts",
    true,
    "Name or short message",
    40,
    "photo-1513475382585-d06e58bcb0e0",
  ],
  [
    "Marigold Door Hanging",
    "marigold-door-hanging",
    "A reusable fabric marigold hanging made for doorways, mantels, and joyful entrances.",
    "A brighter welcome.",
    "RF-MARIGOLD-016",
    799,
    28,
    "rakhi-festive",
    false,
    null,
    null,
    "photo-1478146896981-b80fe463b330",
  ],
  [
    "Stoneware Serving Bowl",
    "stoneware-serving-bowl",
    "A wheel-thrown serving bowl with a quiet speckled glaze and generous curve.",
    "Gather around something made well.",
    "HD-BOWL-017",
    1699,
    9,
    "home-decor",
    false,
    null,
    null,
    "photo-1610701596007-11502861dcfa",
  ],
  [
    "Handpainted Silk Scrunchie Trio",
    "handpainted-silk-scrunchie-trio",
    "Three soft silk scrunchies made from handpainted offcuts in complementary tones.",
    "Small luxuries, thoughtfully made.",
    "JA-SILK-018",
    699,
    32,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1596462502278-27bfdc403348",
  ],
  [
    "Engraved Leather Journal",
    "engraved-leather-journal",
    "A hand-bound leather journal with personalised initials embossed on the cover.",
    "For thoughts worth keeping.",
    "PG-JOURNAL-019",
    1399,
    26,
    "personalized-gifts",
    true,
    "Initials to emboss",
    3,
    "photo-1544816155-12df9643f363",
  ],
  [
    "Sandalwood Beard Grooming Kit",
    "sandalwood-beard-grooming-kit",
    "A curated grooming kit with sandalwood beard oil, comb, and balm in a wooden box.",
    "Everyday ritual, elevated.",
    "PG-GROOM-020",
    1799,
    20,
    "personalized-gifts",
    false,
    null,
    null,
    "photo-1621607512214-68297480165e",
  ],
  [
    "Handloom Pashmina Shawl",
    "handloom-pashmina-shawl",
    "A feather-soft handloom pashmina shawl woven in a warm heritage palette.",
    "Wrapped in warmth.",
    "JA-SHAWL-021",
    3499,
    12,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1520903920243-00d872a2d1c9",
  ],
  [
    "Rose Gold Meenakari Bangles",
    "rose-gold-meenakari-bangles",
    "A set of two rose-gold finish bangles with delicate hand-painted meenakari work.",
    "Colour that stays with you.",
    "JA-BANGLE-022",
    1899,
    18,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1611591437281-460bfbe1220a",
  ],
  [
    "Leather Card Wallet",
    "leather-card-wallet",
    "A slim, hand-stitched leather card wallet that ages beautifully with use.",
    "Refined, everyday carry.",
    "PG-WALLET-023",
    1199,
    30,
    "personalized-gifts",
    true,
    "Initials to emboss",
    3,
    "photo-1627123424574-724758594e93",
  ],
  [
    "Wooden Toy Train Set",
    "wooden-toy-train-set",
    "A hand-carved wooden train set finished with child-safe natural colours.",
    "Play that lasts generations.",
    "HD-TRAIN-024",
    1299,
    22,
    "home-decor",
    false,
    null,
    null,
    "photo-1558877385-8c1b8e6b6b8b",
  ],
  [
    "Hand-Poured Soy Candle Duo",
    "hand-poured-soy-candle-duo",
    "Two hand-poured soy candles scented with oudh and jasmine in reusable glasses.",
    "Slow evenings, softly lit.",
    "HD-CANDLE-025",
    999,
    40,
    "home-decor",
    false,
    null,
    null,
    "photo-1602874801007-bd458bb1b8b6",
  ],
  [
    "Couple's Engraved Keychain Pair",
    "couples-engraved-keychain-pair",
    "A pair of brass keychains engraved with names or a shared date.",
    "Two halves, one story.",
    "PG-KEYCHAIN-026",
    699,
    50,
    "personalized-gifts",
    true,
    "Two names or a date",
    24,
    "photo-1606760227091-3dd870d97f1d",
  ],
  [
    "Warli Art Coffee Mug Set",
    "warli-art-coffee-mug-set",
    "A pair of ceramic mugs hand-painted with traditional Warli tribal art.",
    "Mornings made meaningful.",
    "HD-MUG-027",
    849,
    36,
    "home-decor",
    false,
    null,
    null,
    "photo-1514228742587-6b1558fcca3d",
  ],
  [
    "Silk Thread Jhumka Earrings",
    "silk-thread-jhumka-earrings",
    "Vibrant silk-thread jhumkas handcrafted with tiny gold-tone bells.",
    "A little music when you move.",
    "JA-JHUMKA-028",
    799,
    28,
    "jewelry-accessories",
    false,
    null,
    null,
    "photo-1535632066927-ab7c9ab60908",
  ],
  [
    "Personalized Star Map Frame",
    "personalized-star-map-frame",
    "A framed print of the night sky from any date and place that matters to them.",
    "The night you'll never forget.",
    "PG-STARMAP-029",
    1599,
    24,
    "personalized-gifts",
    true,
    "Date & place",
    40,
    "photo-1462331940025-496dfbfc7564",
  ],
  [
    "Miniature Elephant Brass Figurine",
    "miniature-elephant-brass-figurine",
    "A hand-cast brass elephant, a symbol of luck and grace, for desk or shelf.",
    "A small blessing, beautifully cast.",
    "HD-ELEPHANT-030",
    1099,
    30,
    "home-decor",
    false,
    null,
    null,
    "photo-1524230572899-a752b3835840",
  ],
] as const;

// Recipient-based tags for gift navigation (Gifts for Her / Him / Kids / Couples)
const recipientTags: Record<string, string[]> = {
  "monogrammed-linen-keepsake-box": ["for-her"],
  "handpainted-silk-scrunchie-trio": ["for-her"],
  "kundan-hair-pin-set": ["for-her"],
  "dhokra-leaf-earrings": ["for-her"],
  "handwoven-cotton-stole": ["for-her"],
  "handloom-pashmina-shawl": ["for-her"],
  "rose-gold-meenakari-bangles": ["for-her"],
  "silk-thread-jhumka-earrings": ["for-her"],
  "beaded-silk-potli": ["for-her"],
  "sandalwood-beard-grooming-kit": ["for-him"],
  "leather-card-wallet": ["for-him"],
  "custom-engraved-desk-tray": ["for-him"],
  "engraved-leather-journal": ["for-him", "for-her"],
  "wooden-toy-train-set": ["for-kids"],
  "warli-art-coffee-mug-set": ["for-couples", "for-her", "for-him"],
  "couples-engraved-keychain-pair": ["for-couples"],
  "personalized-star-map-frame": ["for-couples", "for-her", "for-him"],
  "hand-poured-soy-candle-duo": ["for-her", "for-couples"],
  "personalized-brass-name-plate": ["for-couples"],
};

async function main() {
  const categoryMap = new Map<string, string>();
  for (const category of categories) {
    const record = await prisma.category.upsert({
      where: { slug: category.slug },
      update: category,
      create: category,
    });
    categoryMap.set(category.slug, record.id);
  }

  for (const [
    name,
    slug,
    description,
    shortDescription,
    sku,
    price,
    stock,
    categorySlug,
    customizationEnabled,
    customizationLabel,
    customizationMaxLength,
    imageSeed,
  ] of products) {
    const baseOccasions =
      categorySlug === "rakhi-festive"
        ? ["festivals", "rakhi"]
        : categorySlug === "personalized-gifts"
          ? ["birthdays", "weddings", "housewarming"]
          : ["birthdays", "festivals"];
    const metadata = {
      occasionTags: [...baseOccasions, ...(recipientTags[slug] ?? [])],
      colors:
        categorySlug === "jewelry-accessories"
          ? ["gold", "multicolour"]
          : categorySlug === "home-decor"
            ? ["natural", "terracotta"]
            : ["gold", "red"],
      materials:
        categorySlug === "home-decor"
          ? ["wood", "metal", "clay"]
          : categorySlug === "jewelry-accessories"
            ? ["silk", "brass"]
            : ["brass", "cotton"],
      salesCount: Math.max(8, 100 - stock * 2),
    };
    await prisma.product.upsert({
      where: { slug },
      update: {
        name,
        description,
        shortDescription,
        sku,
        price,
        stock,
        images: [image(imageSeed)],
        status: ProductStatus.ACTIVE,
        customizationEnabled,
        customizationLabel,
        customizationMaxLength,
        categoryId: categoryMap.get(categorySlug)!,
        ...metadata,
      },
      create: {
        name,
        slug,
        description,
        shortDescription,
        sku,
        price,
        stock,
        images: [image(imageSeed)],
        status: ProductStatus.ACTIVE,
        customizationEnabled,
        customizationLabel,
        customizationMaxLength,
        categoryId: categoryMap.get(categorySlug)!,
        ...metadata,
      },
    });
  }

  const adminPassword = process.env.ADMIN_SEED_PASSWORD ?? "DivineAdmin123!";
  const passwordHash = await bcrypt.hash(adminPassword, 12);
  const staffAccounts = [
    {
      name: "Divine Karigari Admin",
      email: "admin@divinekarigari.in",
      role: StaffRole.SUPER_ADMIN,
    },
    {
      name: "Order Manager",
      email: "orders@divinekarigari.in",
      role: StaffRole.ORDER_MANAGER,
    },
    {
      name: "Inventory Manager",
      email: "inventory@divinekarigari.in",
      role: StaffRole.INVENTORY_MANAGER,
    },
  ];

  for (const account of staffAccounts) {
    const user = await prisma.user.upsert({
      where: { email: account.email },
      update: {
        name: account.name,
        passwordHash,
        role: UserRole.STAFF,
      },
      create: {
        name: account.name,
        email: account.email,
        passwordHash,
        role: UserRole.STAFF,
      },
    });
    await prisma.staff.upsert({
      where: { userId: user.id },
      update: { role: account.role, active: true },
      create: { userId: user.id, role: account.role },
    });
  }
}

main().finally(() => prisma.$disconnect());
